name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tests/run-tests.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: wei18/local-composite-action/.github/composite-actions/example@main
