name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: wei18/local-composite-action/.github/composite-actions/example@main
